### ISSUE TITLE
CSS colour of the month tracker

### ISSUE THREAD

**Issue by huijing** [SingaporeCSS/talk.css#1]
- [ ] maroon `#800000` `rgba(128,0,0,1)`
- [ ] darkred `#8B0000` `rgba(139,0,0,1)`
- [ ] brown `#A52A2A` `rgba(165,42,42,1)`
- [x] firebrick `#B22222` `rgba(178,34,34,1)` (at Talk.CSS 17, May 31 2017)
- [ ] rosybrown `#BC8F8F` `rgba(188,143,143,1)`
- [ ] indianred `#CD5C5C` `rgba(205,92,92,1)`
- [x] lightcoral `#F08080` `rgba(240,128,128,1)` (at Talk.CSS 51, Jun 3 2020)
- [ ] red `#FF0000` `rgba(255,0,0,1)`
- [x] snow `#FFFAFA` `rgba(255,250,250,1)` (at Talk.CSS 42, Aug 7, 2019)
- [ ] mistyrose `#FFE4E1` `rgba(255,228,225,1)`
- [ ] salmon `#FA8072` `rgba(250,128,114,1)`
- [x] tomato `#FF6347` `rgba(255,99,71,1)` (at Talk.CSS 22, Oct 26 2017)
- [ ] darksalmon `#E9967A` `rgba(233,150,122,1)`
- [x] coral `#FF7F50` `rgba(255,127,80,1)` (at Talk.CSS 37, Mar 27 2019)
- [x] orangered `#FF4500` `rgba(255,69,0,1)` (at Talk.CSS 35, Jan 30 2019)
- [ ] lightsalmon `#FFA07A` `rgba(255,160,122,1)`
- [x] sienna `#A0522D` `rgba(160,82,45,1)` (at Talk.CSS 48, Mar 4 2020)
- [ ] seashell `#FFF5EE` `rgba(255,245,238,1)`
- [ ] saddlebrown `#8B4513` `rgba(139,69,19,1)`
- [x] chocolate `#D2691E` `rgba(210,105,30,1)` (at Talk.CSS 18, Jun 28 2017)
- [ ] sandybrown `#F4A460` `rgba(244,164,96,1)`
- [ ] peachpuff `#FFDAB9` `rgba(255,218,185,1)`
- [x] peru `#CD853F` `rgba(205,133,63,1)` (at Talk.CSS 31, Aug 29 2018)
- [ ] linen `#FAF0E6` `rgba(250,240,230,1)`
- [ ] bisque `#FFE4C4` `rgba(255,228,196,1)`
- [x] darkorange `#FF8C00` `rgba(255,140,0,1)` (at Talk.CSS 33, Oct 31 2018)
- [ ] burlywood `#DEB887` `rgba(222,184,135,1)`
- [ ] tan `#D2B48C` `rgba(210,180,140,1)`
- [ ] antiquewhite `#FAEBD7` `rgba(250,235,215,1)`
- [ ] navajowhite `#FFDEAD` `rgba(255,222,173,1)`
- [ ] blanchedalmond `#FFEBCD` `rgba(255,235,205,1)`
- [x] papayawhip `#FFEFD5` `rgba(255,239,213,1)` (at Talk.CSS 27, Apr 25 2018)
- [ ] moccasin `#FFE4B5` `rgba(255,228,181,1)`
- [x] orange `#FFA500` `rgba(255,165,0,1)` (at Talk.CSS 43, Sep 4 2019)
- [ ] wheat `#F5DEB3` `rgba(245,222,179,1)`
- [ ] oldlace `#FDF5E6` `rgba(253,245,230,1)`
- [ ] floralwhite `#FFFAF0` `rgba(255,250,240,1)`
- [ ] darkgoldenrod `#B8860B` `rgba(184,134,11,1)`
- [x] goldenrod `#DAA520` `rgba(218,165,32,1)` (at Talk.CSS 53, Aug 5 2020)
- [ ] cornsilk `#FFF8DC` `rgba(255,248,220,1)`
- [ ] gold `#FFD700` `rgba(255,215,0,1)`
- [ ] khaki `#F0E68C` `rgba(240,230,140,1)`
- [x] lemonchiffon `#FFFACD` `rgba(255,250,205,1)` (at Talk.CSS 14, Feb 27 2017)
- [ ] palegoldenrod `#EEE8AA` `rgba(238,232,170,1)`
- [ ] darkkhaki `#BDB76B` `rgba(189,183,107,1)`
- [ ] olive `#808000` `rgba(128,128,0,1)`
- [ ] beige `#F5F5DC` `rgba(245,245,220,1)`
- [x] lightgoldenrodyellow `#FAFAD2` `rgba(250,250,210,1)` (at Talk.CSS 44, Oct 2 2019)
- [ ] yellow `#FFFF00` `rgba(255,255,0,1)`
- [ ] lightyellow `#FFFFE0` `rgba(255,255,224,1)`
- [ ] ivory `#FFFFF0` `rgba(255,255,240,1)`
- [x] olivedrab `#6B8E23` `rgba(107,142,35,1)` (at Talk.CSS 32, Sep 26 2018)
- [x] yellowgreen `#9ACD32` `rgba(154,205,50,1)` (at Talk.CSS 55, Oct 7 2020)
- [ ] darkolivegreen `#556B2F` `rgba(85,107,47,1)`
- [ ] greenyellow `#ADFF2F` `rgba(173,255,47,1)`
- [x] chartreuse `#7FFF00` `rgba(127,255,0,1)` (at Talk.CSS 15, Mar 29 2017)
- [ ] lawngreen `#7CFC00` `rgba(124,252,0,1)`
- [ ] darkseagreen `#8FBC8F` `rgba(143,188,143,1)`
- [ ] darkgreen `#006400` `rgba(0,100,0,1)`
- [ ] green `#008000` `rgba(0,128,0,1)`
- [x] lime `#00FF00` `rgba(0,255,0,1)` (at Talk.CSS 25, Feb 28 2018)
- [ ] forestgreen `#228B22` `rgba(34,139,34,1)`
- [ ] limegreen `#32CD32` `rgba(50,205,50,1)`
- [ ] lightgreen `#90EE90` `rgba(144,238,144,1)`
- [ ] palegreen `#98FB98` `rgba(152,251,152,1)`
- [ ] honeydew `#F0FFF0` `rgba(240,255,240,1)`
- [ ] seagreen `#2E8B57` `rgba(46,139,87,1)`
- [x] mediumseagreen `#3CB371` `rgba(60,179,113,1)` (at Talk.CSS 45, Nov 6 2019)
- [ ] springgreen `#00FF7F` `rgba(0,255,127,1)`
- [ ] mintcream `#F5FFFA` `rgba(245,255,250,1)`
- [ ] mediumspringgreen `#00FA9A` `rgba(0,250,154,1)`
- [ ] mediumaquamarine `#66CDAA` `rgba(102,205,170,1)`
- [x] aquamarine `#7FFFD4` `rgba(127,255,212,1)` (at Talk.CSS 30, Jul 25 2018)
- [ ] turquoise `#40E0D0` `rgba(64,224,208,1)`
- [x] lightseagreen `#20B2AA` `rgba(32,178,170,1)` (at Talk.CSS 40, Jun 12 2019)
- [ ] mediumturquoise `#48D1CC` `rgba(72,209,204,1)`
- [ ] teal `#008080` `rgba(0,128,128,1)`
- [ ] darkcyan `#008B8B` `rgba(0,139,139,1)`
- [ ] aqua `#00FFFF` `rgba(0,255,255,1)`
- [x] cyan `#00FFFF` `rgba(0,255,255,1)` (at Talk.CSS 39, May 22 2019)
- [ ] darkslategray `#2F4F4F` `rgba(47,79,79,1)`
- [ ] darkslategrey `#2F4F4F` `rgba(47,79,79,1)`
- [ ] paleturquoise `#AFEEEE` `rgba(175,238,238,1)`
- [ ] lightcyan `#E0FFFF` `rgba(224,255,255,1)`
- [ ] azure `#F0FFFF` `rgba(240,255,255,1)`
- [ ] darkturquoise `#00CED1` `rgba(0,206,209,1)`
- [ ] cadetblue `#5F9EA0` `rgba(95,158,160,1)`
- [x] powderblue `#B0E0E6` `rgba(176,224,230,1)` (at Talk.CSS 54, Sept 2 2020)
- [ ] lightblue `#ADD8E6` `rgba(173,216,230,1)`
- [x] deepskyblue `#00BFFF` `rgba(0,191,255,1)` (at Talk.CSS 19, Jul 26 2017)
- [ ] skyblue `#87CEEB` `rgba(135,206,235,1)`
- [ ] lightskyblue `#87CEFA` `rgba(135,206,250,1)`
- [x] steelblue `#4682B4` `rgba(70,130,180,1)` (at Talk.CSS 41, Jul 3 2019)
- [x] aliceblue `#F0F8FF` `rgba(240,248,255,1)` (at Talk.CSS 46, Jan 8 2020)
- [x] dodgerblue `#1E90FF` `rgba(30,144,255,1)` (at Talk.CSS 16, Apr 26 2017)
- [ ] slategray `#708090` `rgba(112,128,144,1)`
- [ ] slategrey `#708090` `rgba(112,128,144,1)`
- [ ] lightslategray `#778899` `rgba(119,136,153,1)`
- [ ] lightslategrey `#778899` `rgba(119,136,153,1)`
- [x] lightsteelblue `#B0C4DE` `rgba(176,196,222,1)` (at Talk.CSS 29, Jun 28 2018)
- [x] cornflowerblue `#6495ED` `rgba(100,149,237,1)` (at Talk.CSS 50, May 6 2020)
- [ ] royalblue `#4169E1` `rgba(65,105,225,1)`
- [ ] navy `#000080` `rgba(0,0,128,1)`
- [ ] darkblue `#00008B` `rgba(0,0,139,1)`
- [x] mediumblue `#0000CD` `rgba(0,0,205,1)` (at Talk.CSS 52, Jul 1 2020)
- [ ] blue `#0000FF` `rgba(0,0,255,1)`
- [x] midnightblue `#191970` `rgba(25,25,112,1)` (at Talk.CSS 34, Nov 28 2018)
- [ ] lavender `#E6E6FA` `rgba(230,230,250,1)`
- [x] ghostwhite `#F8F8FF` `rgba(248,248,255,1)` (at Talk.CSS 20, Aug 30 2017)
- [ ] slateblue `#6A5ACD` `rgba(106,90,205,1)`
- [ ] darkslateblue `#483D8B` `rgba(72,61,139,1)`
- [x] mediumslateblue `#7B68EE` `rgba(123,104,238,1)` (at Talk.CSS 49, Apr 1 2020)
- [ ] mediumpurple `#9370DB` `rgba(147,112,219,1)`
- [x] rebeccapurple `#663399` `rgba(102,51,153,1)` (at Talk.CSS 56, Nov 4 2020)
- [ ] blueviolet `#8A2BE2` `rgba(138,43,226,1)`
- [x] indigo `#4B0082` `rgba(75,0,130,1)` (at Talk.CSS 26, Mar 28 2018)
- [ ] darkorchid `#9932CC` `rgba(153,50,204,1)`
- [ ] darkviolet `#9400D3` `rgba(148,0,211,1)`
- [ ] mediumorchid `#BA55D3` `rgba(186,85,211,1)`
- [ ] purple `#800080` `rgba(128,0,128,1)`
- [ ] darkmagenta `#8B008B` `rgba(139,0,139,1)`
- [ ] thistle `#D8BFD8` `rgba(216,191,216,1)`
- [ ] plum `#DDA0DD` `rgba(221,160,221,1)`
- [ ] violet `#EE82EE` `rgba(238,130,238,1)`
- [x] fuchsia `#FF00FF` `rgba(255,0,255,1)`  (at Talk.CSS 28, May 30 2018)
- [ ] magenta `#FF00FF` `rgba(255,0,255,1)`
- [ ] orchid `#DA70D6` `rgba(218,112,214,1)`
- [x] mediumvioletred `#C71585` `rgba(199,21,133,1)` (at Talk.CSS 36, Feb 27 2019)
- [ ] deeppink `#FF1493` `rgba(255,20,147,1)`
- [ ] hotpink `#FF69B4` `rgba(255,105,180,1)`
- [ ] lavenderblush `#FFF0F5` `rgba(255,240,245,1)`
- [ ] palevioletred `#DB7093` `rgba(219,112,147,1)`
- [x] crimson `#DC143C` `rgba(220,20,60,1)` (at Talk.CSS 23, Nov 29 2017)
- [ ] pink `#FFC0CB` `rgba(255,192,203,1)`
- [ ] lightpink `#FFB6C1` `rgba(255,182,193,1)`
- [x] black `#000000` `rgba(0,0,0,1)` (at Talk.CSS 38, Apr 24 2019)
- [ ] dimgray `#696969` `rgba(105,105,105,1)`
- [ ] dimgrey `#696969` `rgba(105,105,105,1)`
- [ ] gray `#808080` `rgba(128,128,128,1)`
- [ ] grey `#808080` `rgba(128,128,128,1)`
- [ ] darkgray `#A9A9A9` `rgba(169,169,169,1)`
- [ ] darkgrey `#A9A9A9` `rgba(169,169,169,1)`
- [ ] silver `#C0C0C0` `rgba(192,192,192,1)`
- [ ] lightgray `#D3D3D3` `rgba(211,211,211,1)`
- [ ] lightgrey `#D3D3D3` `rgba(211,211,211,1)`
- [x] gainsboro `#DCDCDC` `rgba(220,220,220,1)` (at Talk.CSS 21, Sep 26 2017)
- [ ] whitesmoke `#F5F5F5` `rgba(245,245,245,1)`
- [ ] white `#FFFFFF` `rgba(255,255,255,1)`
